//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vfi.rc
//
#define IDD_ABOUTBOX                    100
#define CG_POPUP                        101
#define STR_APPNAME                     101
#define STR_APPTITLE                    101
#define IDD_COLUMNOPTIONS               103
#define IDR_MAINFRAME                   104
#define IDD_GENERALOPTIONS              109
#define IDD_PROGRESS                    110
#define IDD_TIMEBOX                     131
#define IDR_RTF_HELP                    132
#define IDD_RTFHELP                     138
#define WAV_COMPLETE                    139
#define OLD_IDD_GENERALOPTIONS          140
#define IDI_ASCEND                      143
#define IDI_DESCEND                     144
#define FONT_TAHOMA                     150
#define FONT_TAHOMA_BOLD                151
#define IDR_MENUNEW                     155
#define IDR_MAINFRAMED                  155
#define IDD_TESTINFO                    157
#define IDR_RTF_ISO                     159
#define IDR_RTF_OS                      161
#define IDR_RTF_TYPE                    162
#define IDR_RTF_VERSION                 163
#define IDR_RTF_FLAGS                   164
#define IDR_RTF_CRC                     165
#define IDR_RTF_ATTRIBS                 166
#define IDR_RTF_CODEPAGE                167
#define IDR_RTF_LANGUAGE                168
#define IDD_DIALOG1                     170
#define IDB_BACKGROUND                  173
#define IDB_TOOLBARHOT                  174
#define IDB_TOOLBARCOLD                 175
#define IDR_ACCELERATOR1                183
#define ID_VIEW_ISOFLAGS                184
#define IDS_PROPSHT_CAPTION             200
#define STR_MOREDIRTYFILES              201
#define STR_DIRTYSAVE                   201
#define STR_INIFILENAME                 202
#define STR_HEADERS                     203
#define STR_TITLE                       204
#define STR_TITLE_TOOLS                 205
#define STR_DIRTYCOPY                   206
#define IDS_STRING300                   300
#define ERR_FILECLOSE                   301
#define ERR_FILEOPEN                    302
#define ERR_NOMEMORY                    303
#define ERR_HEAP                        304
#define ERR_NOTOUCH                     305
#define ERR_NODELETE                    306
#define ERR_BADDRIVE                    307
#define ERR_NOSPACE                     308
#define ERR_ADDFILE_FAILED              309
#define ERR_INSTALL                     310
#define ERR_WAVENOTFOUND                311
#define ERR_REENTERWAVE                 312
#define ERR_FILEINUSE                   313
#define ERR_IE4                         314
#define ERR_COMCTL                      314
#define ERR_HELPTOPICNOTFOUND           315
#define ERR_WIN9XTHUNKBUG               316
#define ERR_NONETWORK                   317
#define ERR_BADCOMMANDLINE              318
#define ERR_VXDWARN                     319
#define ERR_TITLE                       320
#define ERR_SAVEGENERAL                 321
#define ERR_CLIPBOARD                   322
#define ERR_REENTERPATH                 323
#define ERR_SHELLMEMORY                 324
#define STR_COLUMN0                     400
#define STR_COLUMN1                     401
#define STR_COLUMN2                     402
#define STR_COLUMN3                     403
#define STR_COLUMN4                     404
#define STR_COLUMN5                     405
#define STR_COLUMN6                     406
#define STR_COLUMN7                     407
#define STR_COLUMN8                     408
#define STR_COLUMN9                     409
#define STR_COLUMN10                    410
#define STR_COLUMN11                    411
#define STR_COLUMN12                    412
#define STR_COLUMN13                    413
#define STR_COLUMN14                    414
#define STR_COLUMN15                    415
#define STR_COLUMN16                    416
#define STR_COLUMN17                    417
#define STR_COLUMN18                    418
#define STR_COLUMN19                    419
#define IDS_STRING500                   500
#define STR_FILEFILTER                  501
#define STR_SAVEMODIFIED                502
#define STR_SAVEAS                      503
#define STR_THREADSTOP                  504
#define STR_EMPTYTRASH                  505
#define STR_CRC_ENDING                  506
#define STR_BROWSETITLE                 507
#define STR_FILEADD                     508
#define STR_INITFILE                    509
#define STR_LEAKCRCTHREAD               510
#define STR_LEAKINFOTHREAD              511
#define STR_SAVEFILTER                  512
#define STR_FILECOUNT                   513
#define STR_SIZEMB                      514
#define STR_SIZEKB                      515
#define STR_RELAUNCHTOCHANGE            516
#define STR_RECURSEFOLDER               517
#define STR_BROWSEWAVE                  518
#define STR_WAVEFILTER                  519
#define STR_RESERVED                    520
#define STR_FILETOUCH                   521
#define STR_GETTINGINFO                 522
#define STR_GETTINGCRC                  523
#define STR_DONE                        524
#define STR_FILEREMOVE                  525
#define STR_BUFFERMB                    526
#define STR_FILECOUNTING                526
#define STR_MB                          527
#define STR_KB                          528
#define STR_AUTHORFULL                  529
#define STR_AUTHOR                      530
#define STR_OPENTITLE                   531
#define STR_BROWSESAVE                  532
#define STR_FILESAVING                  533
#define STR_COPTONS                     534
#define STR_COPYTONS                    534
#define IDS_STRING600                   600
#define STR_ISO_PATHTOOLONG             601
#define STR_ISO_PATHBADCHAR             602
#define STR_ISO_PATHHASDOT              603
#define STR_ISO_PATHTOODEEP             604
#define STR_ISO_FILETOOLONG             605
#define STR_ISO_FILEBADCHAR             606
#define STR_ISO_FILEHASDOT              607
#define STR_ISO_EXTTOOLONG              608
#define STR_ISO_EXTBADCHAR              609
#define STR_ISO_EXTHASDOT               610
#define STR_ISO_PATHLOWERCASE           611
#define STR_ISO_FILELOWERCASE           612
#define STR_ISO_EXTLOWERCASE            613
#define IDS_STRING700                   700
#define STR_FLAG_DEBUG                  701
#define STR_FLAG_PRERELEASE             702
#define STR_FLAG_PATCHED                703
#define STR_FLAG_PRIVATEBUILD           704
#define STR_FLAG_INFOINFERRED           705
#define STR_FLAG_SPECIALBUILD           706
#define STR_FLAG_DEBUG_STRIPPED         707
#define IDS_STRING800                   800
#define STR_MENUVIEW_HEXSIZE            801
#define STR_MENUVIEW_DECSIZE            802
#define STR_MENUVIEW_LANGNAME           803
#define STR_MENUVIEW_LANGID             804
#define STR_MENUVIEW_HEXCRC             805
#define STR_MENUVIEW_DECCRC             806
#define STR_MENUVIEW_GMTIME             807
#define STR_MENUVIEW_LOCALTIME          808
#define STR_MENU_FILE                   850
#define STR_MENU_EDIT                   851
#define STR_MENU_VIEW                   852
#define STR_MENU_HELP                   853
#define IDS_STRING900                   900
#define STR_TEST_DISKSPACE              901
#define TIPS                            1000
#define TIP_PROGRESS_CRC                1001
#define IDC_PROGRESS1                   1002
#define TIP_COUNT                       1002
#define IDC_AUDIOCUE                    1003
#define TIP_SIZE                        1003
#define IDC_EDITWAVE                    1004
#define TIP_BUFFER                      1004
#define IDC_BROWSEWAVE                  1005
#define TIP_PROGRESS_INFO               1005
#define IDC_ALLOWFOLDERS                1006
#define IDC_ISOINCLUDEPATH              1007
#define IDC_GENERATECRC                 1008
#define IDC_SAVEPROMPT                  1008
#define IDC_GRIDLINES                   1009
#define IDC_WARNVXD                     1009
#define IDC_WARNPATH                    1010
#define IDC_SAVEPATH                    1011
#define IDC_BROWSEPATH                  1012
#define IDC_TIMEPICK                    1016
#define psh15                           0x040e
#define chx1                            0x0410
#define IDC_LISTCOLUMNS                 1044
#define IDC_CLEARALL                    1045
#define IDC_CHECKALL                    1046
#define IDC_SLIDER                      1049
#define IDC_MSG_MEMORY                  1052
#define IDC_RICHEDIT                    1053
#define IDC_TITLE                       1054
#define IDC_DATEPICK                    1060
#define IDC_COMPACT                     1067
#define IDC_TEXT                        1068
#define IDC_SYSINFO                     1069
#define IDC_DISPLAYAGAIN                1070
#define IDC_MEMORY                      1071
#define IDC_AUTHOR                      1072
#define IDC_MEMORY2                     1073
#define IDC_EVENTINFO                   1073
#define IDC_BUTTON1                     1075
#define IDC_MONTHCALENDAR1              1077
#define lst1                            0x0460
#define lst2                            0x0461
#define cmb1                            0x0470
#define cmb2                            0x0471
#define edt1                            0x0480
#define STR_CRC_ERROR                   2001
#define STR_CRC_PENDING                 2002
#define STR_CRC_WORKING                 2003
#define ID_FILE_ADD                     32768
#define ID_FILE_SAVEAS                  32769
#define ID_FILE_INFORMATION             32770
#define ID_VIEW_TOOLTIPS                32771
#define ID_VIEW_TIME                    32775
#define ID_VIEW_LANGUAGE                32776
#define ID_VIEW_FILESIZE                32777
#define ID_VIEW_CRC                     32778
#define ID_VIEW_OPTIONS                 32779
#define ID_KEYDOWN                      32781
#define ID_KEYUP                        32782
#define ID_KEYSPACE                     32783
#define ID_FILE_RECURSEDIR              32784
#define ID_FILE_DELETE                  32787
#define ID_FILE_RENAME                  32788
#define ID_FILE_TOUCH                   32789
#define DEBUG_INFO                      32790
#define ID_FILE_CALCCRC                 32792
#define ID_FILE_PROPERTIES              32793
#define ID_EDIT_DELETE                  32794
#define ID_VIEW_SMARTFIT                32797
#define ID_EDIT_REMOVE                  32799
#define ID_FILE_QUICKVIEW               32800
#define ID_MENU_FILE                    32801
#define ID_MENU_EDIT                    32802
#define ID_MENU_VIEW                    32803
#define ID_MENU_HELP                    32804
#define IDM_TEST_INFO                   32805
#define ID_HELP_ATTRIBS                 32806
#define ID_HELP_ISO                     32807
#define ID_HELP_FILEFLAGS               32808
#define ID_HELP_FILETYPE                32809
#define ID_HELP_OS                      32810
#define ID_HELP_CRC                     32811
#define ID_HELP_VERSION                 32812
#define ID_HELP_LANGUAGE                32813
#define ID_HELP_CODEPAGE                32814
#define ID_INDICATOR_COUNT              59140
#define ID_INDICATOR_SIZE               59141
#define ID_PROGRESS                     59142
#define ID_INDICATOR_BUFFER             59394
#define IDS_PANESIZE                    61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
